name: Node.js CI

on:
  push:
    branches:
      - main
      - 'feature/*'
      - 'bugfix/*'
  pull_request_review:
    types: [submitted]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    
    - name: Install dependencies
      run: npm install

    - name: Lint code with ESLint
      run: npm run lint

    - name: Test code
      run: npm test

  merge-to-dev:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/develop'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Ensure no direct push to develop branch
      run: |
        if [ $GITHUB_ACTOR == "github-actions[bot]" ]; then
          echo "Direct push to develop branch is not allowed. Please use pull requests."
          exit 1
        fi

    - name: Request review for merging to develop
      uses: actions/github-script@v4
      with:
        script: |
          const { owner, repo } = context.repo;
          const contributors = await github.repos.listContributors({
            owner,
            repo
          });
          const reviewerUsernames = contributors.data.map(contributor => contributor.login);
          const response = await github.pulls.createReviewRequest({
            owner,
            repo,
            pull_number: context.payload.pull_request.number,
            reviewers: reviewerUsernames
          });
          console.log(response);

  branch-name-check:
    runs-on: ubuntu-latest
    steps:
    - name: Check branch name
      run: |
        BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})
        if ! [[ $BRANCH_NAME =~ ^(main|develop|feature|bugfix)\/[a-z0-9-]+$ ]]; then
          echo "Invalid branch name. Branch names must follow the pattern: (main|develop|feature|bugfix)/[a-z0-9-]+"
          exit 1
        fi
